# Xiaomi Pad 6 Pro defaults
manufacturer=Xiaomi
brand=Xiaomi
model=23046RP50C
device=pipa
product=pipa
marketname=Xiaomi Pad 6 Pro
characteristics=tablet
board=pipa
hardware=qcom
locale=zh-CN
mod_device=pipa
build_product=pipa
cpu_abilist=arm64-v8a,armeabi-v7a,armeabi
cpu_abilist32=armeabi-v7a,armeabi
cpu_abilist64=arm64-v8a
serialno=unknown
boot_serialno=unknown
arch=arm64

# Package names or package sub-processes separated by commas.
targets=com.tencent.mm,com.tencent.mobileqq,com.tencent.tim,com.alibaba.android.rimet
